import { InactiveStyle, MotionPresetId } from "@/types/dot-motion";

export type Language = "cn" | "en";

export const uiCopy = {
  cn: {
    add: "+ 新建",
    previewAll: "全部预览",
    stopPreview: "停止预览",
    export: "导出",
    settings: "设置",
    grid: "网格",
    pattern: "图案",
    animation: "动画",
    colors: "颜色",
    effects: "效果",
    shape: "形状",
    rectangle: "圆角",
    square: "方形",
    circle: "圆形",
    hexagon: "六边形",
    star: "星型",
    diamond: "菱形",
    customMode: "自定义",
    sequenceMode: "序列",
    addFrame: "+ 序列",
    removeFrame: "- 序列",
    primaryColor: "激活颜色",
    glow: "发光",
    spread: "范围",
    backgroundColor: "未激活颜色",
    gridSize: "点阵数量",
    gap: "间距",
    activeCells: "激活点",
    inactiveCells: "未激活点",
    playbackSpeed: "速度",
    direction: "方向",
    originX: "原点 X",
    originY: "原点 Y",
    speed: "速度 (FPS)",
    previewAnimation: "预览动画",
    copyOutput: "复制",
    copied: "已复制",
    downloadFile: "下载",
    closeExport: "关闭导出窗口",
    exportFile: "导出文件"
  },
  en: {
    add: "+ Add",
    previewAll: "Preview All",
    stopPreview: "Stop Preview",
    export: "Export",
    settings: "Settings",
    grid: "Grid",
    pattern: "Pattern",
    animation: "Animation",
    colors: "Colors",
    effects: "Effects",
    shape: "Shape",
    rectangle: "Rounded",
    square: "Square",
    circle: "Circle",
    hexagon: "Hexagon",
    star: "Star",
    diamond: "Diamond",
    customMode: "Custom",
    sequenceMode: "Sequence",
    addFrame: "+ Seq",
    removeFrame: "- Seq",
    primaryColor: "Active Color",
    glow: "Glow",
    spread: "Spread",
    backgroundColor: "Inactive Color",
    gridSize: "Grid Size",
    gap: "Gap",
    activeCells: "Active Cells",
    inactiveCells: "Inactive Cells",
    playbackSpeed: "Speed",
    direction: "Direction",
    originX: "Origin X",
    originY: "Origin Y",
    speed: "Speed (FPS)",
    previewAnimation: "Preview Animation",
    copyOutput: "Copy",
    copied: "Copied",
    downloadFile: "Download",
    closeExport: "Close export panel",
    exportFile: "Export File"
  }
} as const;

export const inactiveStyleCopy: Record<Language, Record<InactiveStyle, string>> = {
  cn: {
    none: "无（静态）",
    "static-dim": "静态暗点",
    breathe: "呼吸",
    ghost: "幽灵网格"
  },
  en: {
    none: "None (Static)",
    "static-dim": "Static Dim",
    breathe: "Breathe",
    ghost: "Ghost Grid"
  }
};

export const motionPresetCopy: Record<Language, Record<MotionPresetId, { name: string; description: string }>> = {
  cn: {
    spinner: {name: "旋转加载", description: "带渐隐尾迹的亮点沿外圈旋转。"},
    radar: {name: "雷达", description: "旋转光束与渐隐尾迹。"},
    orbit: {name: "轨道", description: "亮点沿椭圆轨道连续运行。"},
    heartbeat: {name: "心跳", description: "一强一弱的双脉冲与短暂停顿。"},
    equalizer: {name: "均衡器", description: "各列以不同相位升降。"},
    dna: {name: "DNA 双螺旋", description: "两束波纹交错穿行。"},
    sparkle: {name: "星闪", description: "分散点位错峰亮起，自然渐隐。"},
    breathing: {name: "呼吸", description: "所有选中点阵平滑明暗交替。"},
    sine: {name: "正弦波", description: "横向传播的连续波形。"},
    collapse: {name: "向内收拢", description: "波纹从外侧向指定原点收拢。"},
    wave: { name: "波浪", description: "可向上下左右或对角线推进的错峰波浪。" },
    sweep: { name: "扫描", description: "更干净的扫描前沿，带柔和尾迹。" },
    bloom: { name: "扩散", description: "从指定原点向外扩散的亮度波。" },
    "fish-eye": { name: "鱼眼镜头", description: "复刻参考站的对角亮度波与径向镜头缩放。" },
    spiral: { name: "螺旋", description: "按顺时针螺旋路径依次点亮。" },
    corners: { name: "四角优先", description: "四角先亮，再推进到边缘和中心。" },
    snake: { name: "蛇形", description: "按行列蛇形路径连续游走。" },
    checkerboard: { name: "棋盘", description: "奇偶格分组交替闪烁。" },
    rain: { name: "雨滴", description: "分散落点形成随机雨滴感。" },
    pinwheel: { name: "风车", description: "按角度象限围绕中心旋转推进。" },
    burst: {name: "爆发", description: "单圈从原点向外爆发并逐渐消失。"},
    typewriter: {name: "打字机", description: "按阅读顺序填充，并保留明亮光标。"},
    "row-scan": {name: "逐行扫描", description: "整行从上到下逐步扫描。"},
    "column-scan": {name: "逐列扫描", description: "整列从左到右逐步扫描。"},
    matrix: {name: "矩阵雨", description: "每列以不同速度和长度下落。"},
    glitch: {name: "故障闪烁", description: "短促横向故障打断暗态背景。"},
    random: {name: "随机噪点", description: "可重复的帧噪点在网格中闪烁。"},
    "diamond-wave": {name: "菱形扩散", description: "按曼哈顿距离从原点扩散。"},
    "box-trace": {name: "边框追踪", description: "亮点沿网格外框连续行进。"},
    "cross-wave": {name: "十字呼吸", description: "中心十字明暗呼吸，其余点保持暗态。"},
    "heart-wave": {name: "心形跳动", description: "中心心形以加载节奏跳动。"},
    "letter-t": {name: "字母 T", description: "可复用的动态 T 形点阵。"},
    "letter-x": {name: "字母 X", description: "可复用的动态 X 形点阵。"},
    "letter-o": {name: "字母 O", description: "可复用的动态 O 形点阵。"},
    "thinking-dots": {name: "思考点", description: "三个错相圆点在中线附近弹跳。"},
    "neural-network": {name: "神经网络", description: "中心向外传播的角度与距离复合场。"},
    searching: {name: "搜索中", description: "水平扫描线来回搜索，并保留轻微噪点。"},
    connecting: {name: "连接中", description: "信号从中心节点依次传向四角。"},
    "progress-bar": {name: "进度条", description: "居中的点阵进度条从左到右填充。"},
    success: {name: "完成", description: "对勾沿路径逐步绘制完成。"},
    error: {name: "错误", description: "带轻微抖动的叉号错误状态。"},
    "arrow-right": {name: "向右箭头", description: "柔和箭头前沿从左向右推进。"},
    "arrow-left": {name: "向左箭头", description: "柔和箭头前沿从右向左推进。"},
    hourglass: {name: "沙漏", description: "亮度从上半区逐渐转移到下半区。"}
  },
  en: {
    spinner: {name: "Spinner", description: "A bright head with a fading tail travels around the perimeter."},
    radar: {name: "Radar", description: "Rotating beam with a fading trail."},
    orbit: {name: "Orbit", description: "A soft light follows an elliptical orbit."},
    heartbeat: {name: "Heartbeat", description: "A strong beat followed by a softer echo."},
    equalizer: {name: "Equalizer", description: "Columns rise and fall with independent phases."},
    dna: {name: "DNA Helix", description: "Two waves weave through each other."},
    sparkle: {name: "Sparkle", description: "Scattered lights fade in and out."},
    breathing: {name: "Breathing", description: "Smooth, synchronized breathing."},
    sine: {name: "Sine Wave", description: "A continuous traveling waveform."},
    collapse: {name: "Collapse", description: "Ripples converge on the selected origin."},
    wave: { name: "Wave", description: "A staggered wave that travels horizontally, vertically, or diagonally." },
    sweep: { name: "Sweep", description: "A clean scanning front with a softer trailing edge." },
    bloom: { name: "Bloom", description: "A center-out bloom that expands from a chosen origin point." },
    "fish-eye": { name: "Fish-eye Lens", description: "The reference's diagonal brightness wave with radial lens scaling." },
    spiral: { name: "Spiral", description: "A clockwise spiral path through the grid." },
    corners: { name: "Corners First", description: "Corners fire first, then edges, then the center." },
    snake: { name: "Snake", description: "A continuous row-by-row snake path through the grid." },
    checkerboard: { name: "Checkerboard", description: "Alternating parity groups pulse in a checker rhythm." },
    rain: { name: "Rain", description: "Deterministic scattered drops create a random-rain loading feel." },
    pinwheel: { name: "Pinwheel", description: "Angular quadrants spin around the center like a pinwheel." },
    burst: {name: "Burst", description: "A single ring explodes from the origin and fades."},
    typewriter: {name: "Typewriter", description: "Cells fill in reading order with a bright cursor."},
    "row-scan": {name: "Row Scan", description: "A complete row scans from top to bottom."},
    "column-scan": {name: "Column Scan", description: "A complete column scans from left to right."},
    matrix: {name: "Matrix", description: "Columns fall at different deterministic speeds and lengths."},
    glitch: {name: "Glitch", description: "Short horizontal glitches interrupt a dim idle field."},
    random: {name: "Random", description: "Repeatable frame noise flickers across the grid."},
    "diamond-wave": {name: "Diamond", description: "A Manhattan-distance diamond expands from the origin."},
    "box-trace": {name: "Box Trace", description: "A bright head continuously traces the outside box."},
    "cross-wave": {name: "Cross", description: "The center cross breathes while other cells stay dim."},
    "heart-wave": {name: "Heart", description: "A centered heart silhouette beats with the loading rhythm."},
    "letter-t": {name: "Letter T", description: "A reusable animated T-shaped grid."},
    "letter-x": {name: "Letter X", description: "A reusable animated X-shaped grid."},
    "letter-o": {name: "Letter O", description: "A reusable animated O-shaped grid."},
    "thinking-dots": {name: "Thinking Dots", description: "Three phase-shifted dots bounce around the center row."},
    "neural-network": {name: "Neural Network", description: "A centered field combines angle and distance."},
    searching: {name: "Searching", description: "A horizontal scanner bounces over faint activity."},
    connecting: {name: "Connecting", description: "Signals travel from the center node toward all four corners."},
    "progress-bar": {name: "Progress Bar", description: "A centered dot-matrix bar fills from left to right."},
    success: {name: "Success", description: "A check mark draws itself across the grid."},
    error: {name: "Error", description: "A lightly shaking cross resolves into an error state."},
    "arrow-right": {name: "Arrow Right", description: "A soft arrow front travels from left to right."},
    "arrow-left": {name: "Arrow Left", description: "A soft arrow front travels from right to left."},
    hourglass: {name: "Hourglass", description: "Brightness transfers from the upper bulb to the lower bulb."}
  }
};
