import { InactiveStyle, MotionPresetId } from "@/types/dot-motion";

export type Language = "cn" | "en";

export const uiCopy = {
  cn: {
    add: "+ 新建",
    previewAll: "全部预览",
    stopPreview: "停止预览",
    export: "导出",
    settings: "设置",
    grid: "网格",
    pattern: "图案",
    animation: "动画",
    colors: "颜色",
    effects: "效果",
    shape: "形状",
    rectangle: "圆角",
    square: "方形",
    circle: "圆形",
    hexagon: "六边形",
    star: "星型",
    diamond: "菱形",
    customMode: "自定义",
    sequenceMode: "序列",
    addFrame: "+ 序列",
    removeFrame: "- 序列",
    primaryColor: "激活颜色",
    glow: "发光",
    spread: "范围",
    backgroundColor: "未激活颜色",
    gridSize: "点阵数量",
    gap: "间距",
    activeCells: "激活点",
    inactiveCells: "未激活点",
    playbackSpeed: "速度",
    direction: "方向",
    originX: "原点 X",
    originY: "原点 Y",
    speed: "速度 (FPS)",
    previewAnimation: "预览动画",
    copyOutput: "复制",
    copied: "已复制",
    downloadFile: "下载",
    closeExport: "关闭导出窗口",
    exportFile: "导出文件"
  },
  en: {
    add: "+ Add",
    previewAll: "Preview All",
    stopPreview: "Stop Preview",
    export: "Export",
    settings: "Settings",
    grid: "Grid",
    pattern: "Pattern",
    animation: "Animation",
    colors: "Colors",
    effects: "Effects",
    shape: "Shape",
    rectangle: "Rounded",
    square: "Square",
    circle: "Circle",
    hexagon: "Hexagon",
    star: "Star",
    diamond: "Diamond",
    customMode: "Custom",
    sequenceMode: "Sequence",
    addFrame: "+ Seq",
    removeFrame: "- Seq",
    primaryColor: "Active Color",
    glow: "Glow",
    spread: "Spread",
    backgroundColor: "Inactive Color",
    gridSize: "Grid Size",
    gap: "Gap",
    activeCells: "Active Cells",
    inactiveCells: "Inactive Cells",
    playbackSpeed: "Speed",
    direction: "Direction",
    originX: "Origin X",
    originY: "Origin Y",
    speed: "Speed (FPS)",
    previewAnimation: "Preview Animation",
    copyOutput: "Copy",
    copied: "Copied",
    downloadFile: "Download",
    closeExport: "Close export panel",
    exportFile: "Export File"
  }
} as const;

export const inactiveStyleCopy: Record<Language, Record<InactiveStyle, string>> = {
  cn: {
    none: "无（静态）",
    "static-dim": "静态暗点",
    breathe: "呼吸",
    ghost: "幽灵网格"
  },
  en: {
    none: "None (Static)",
    "static-dim": "Static Dim",
    breathe: "Breathe",
    ghost: "Ghost Grid"
  }
};

export const motionPresetCopy: Record<Language, Record<MotionPresetId, { name: string; description: string }>> = {
  cn: {
    radar: {name: "雷达", description: "旋转光束与渐隐尾迹。"},
    orbit: {name: "轨道", description: "亮点沿椭圆轨道连续运行。"},
    heartbeat: {name: "心跳", description: "一强一弱的双脉冲与短暂停顿。"},
    equalizer: {name: "均衡器", description: "各列以不同相位升降。"},
    dna: {name: "DNA 双螺旋", description: "两束波纹交错穿行。"},
    sparkle: {name: "星闪", description: "分散点位错峰亮起，自然渐隐。"},
    breathing: {name: "呼吸", description: "所有选中点阵平滑明暗交替。"},
    sine: {name: "正弦波", description: "横向传播的连续波形。"},
    collapse: {name: "向内收拢", description: "波纹从外侧向指定原点收拢。"},
    blink: { name: "闪烁", description: "选中点阵同步双闪，适合短促状态反馈。" },
    wave: { name: "波浪", description: "可向上下左右或对角线推进的错峰波浪。" },
    sweep: { name: "扫描", description: "更干净的扫描前沿，带柔和尾迹。" },
    bloom: { name: "扩散", description: "从指定原点向外扩散的亮度波。" },
    "fish-eye": { name: "鱼眼波纹", description: "带轻微鱼眼缩放的对角波纹，节奏更柔和。" },
    ripple: { name: "涟漪", description: "从中心或指定原点向外扩散的径向涟漪。" },
    pulse: { name: "脉冲", description: "所有选中点阵一起呼吸闪动。" },
    spiral: { name: "螺旋", description: "按顺时针螺旋路径依次点亮。" },
    corners: { name: "四角优先", description: "四角先亮，再推进到边缘和中心。" },
    snake: { name: "蛇形", description: "按行列蛇形路径连续游走。" },
    checkerboard: { name: "棋盘", description: "奇偶格分组交替闪烁。" },
    rain: { name: "雨滴", description: "分散落点形成随机雨滴感。" },
    pinwheel: { name: "风车", description: "按角度象限围绕中心旋转推进。" }
  },
  en: {
    blink: { name: "Blink", description: "A compact double-flash preset for selected dots." },
    radar: {name: "Radar", description: "Rotating beam with a fading trail."},
    orbit: {name: "Orbit", description: "A soft light follows an elliptical orbit."},
    heartbeat: {name: "Heartbeat", description: "A strong beat followed by a softer echo."},
    equalizer: {name: "Equalizer", description: "Columns rise and fall with independent phases."},
    dna: {name: "DNA Helix", description: "Two waves weave through each other."},
    sparkle: {name: "Sparkle", description: "Scattered lights fade in and out."},
    breathing: {name: "Breathing", description: "Smooth, synchronized breathing."},
    sine: {name: "Sine Wave", description: "A continuous traveling waveform."},
    collapse: {name: "Collapse", description: "Ripples converge on the selected origin."},
    wave: { name: "Wave", description: "A staggered wave that travels horizontally, vertically, or diagonally." },
    sweep: { name: "Sweep", description: "A clean scanning front with a softer trailing edge." },
    bloom: { name: "Bloom", description: "A center-out bloom that expands from a chosen origin point." },
    "fish-eye": { name: "Fisheye Ripple", description: "A diagonal ripple with subtle fisheye scaling and a softer rhythm." },
    ripple: { name: "Ripple", description: "A radial ripple that fades and scales from an origin point." },
    pulse: { name: "Pulse", description: "All selected dots breathe together like a classic loader." },
    spiral: { name: "Spiral", description: "A clockwise spiral path through the grid." },
    corners: { name: "Corners First", description: "Corners fire first, then edges, then the center." },
    snake: { name: "Snake", description: "A continuous row-by-row snake path through the grid." },
    checkerboard: { name: "Checkerboard", description: "Alternating parity groups pulse in a checker rhythm." },
    rain: { name: "Rain", description: "Deterministic scattered drops create a random-rain loading feel." },
    pinwheel: { name: "Pinwheel", description: "Angular quadrants spin around the center like a pinwheel." }
  }
};
