import { InactiveStyle, MotionPresetId } from "@/types/dot-motion";

export type Language = "cn" | "en";

export const uiCopy = {
  cn: {
    add: "+ 新建",
    previewAll: "全部预览",
    stopPreview: "停止预览",
    export: "导出",
    settings: "设置",
    empty: "选择一个画板后编辑点阵、外观和动效。",
    appearance: "外观",
    loaderName: "画板名称",
    shape: "形状",
    rectangle: "矩形",
    triangle: "三角形",
    star: "星型",
    diamond: "菱形",
    heart: "爱心",
    customMode: "自定义",
    sequenceMode: "序列",
    addFrame: "+ 序列",
    removeFrame: "- 序列",
    innerRadius: "内半径",
    primaryColor: "主色",
    glow: "发光",
    glowColor: "发光颜色",
    spread: "范围",
    backgroundColor: "背景点阵颜色",
    cornerRadius: "圆角",
    sharp: "直角",
    round: "圆润",
    gridSize: "点阵数量",
    gap: "间距",
    motion: "动效",
    motionPreset: "动效预设",
    direction: "方向",
    originX: "原点 X",
    originY: "原点 Y",
    backgroundStyle: "背景点阵",
    backgroundHelp: "只影响未亮起的背景点阵，不覆盖已选点阵动效。",
    speed: "速度 (FPS)",
    slower: "更慢",
    faster: "更快",
    previewAnimation: "预览动画",
    copyOutput: "复制",
    copied: "已复制",
    downloadFile: "下载",
    closeExport: "关闭导出窗口",
    exportFile: "导出文件"
  },
  en: {
    add: "+ Add",
    previewAll: "Preview All",
    stopPreview: "Stop Preview",
    export: "Export",
    settings: "Settings",
    empty: "Select an artboard to edit dots, appearance, and motion.",
    appearance: "Appearance",
    loaderName: "Loader Name",
    shape: "Shape",
    rectangle: "Rectangle",
    triangle: "Triangle",
    star: "Star",
    diamond: "Diamond",
    heart: "Heart",
    customMode: "Custom",
    sequenceMode: "Sequence",
    addFrame: "+ Seq",
    removeFrame: "- Seq",
    innerRadius: "Inner Radius",
    primaryColor: "Primary Color",
    glow: "Glow",
    glowColor: "Glow Color",
    spread: "Spread",
    backgroundColor: "Background Color",
    cornerRadius: "Corner Radius",
    sharp: "Sharp",
    round: "Round",
    gridSize: "Grid Size",
    gap: "Gap",
    motion: "Motion",
    motionPreset: "Motion Preset",
    direction: "Direction",
    originX: "Origin X",
    originY: "Origin Y",
    backgroundStyle: "Background Style",
    backgroundHelp: "Affects inactive background dots only, without overriding selected-dot motion.",
    speed: "Speed (FPS)",
    slower: "Slower",
    faster: "Faster",
    previewAnimation: "Preview Animation",
    copyOutput: "Copy",
    copied: "Copied",
    downloadFile: "Download",
    closeExport: "Close export panel",
    exportFile: "Export File"
  }
} as const;

export const inactiveStyleCopy: Record<Language, Record<InactiveStyle, string>> = {
  cn: {
    none: "无（静态）",
    "static-dim": "静态暗点",
    breathe: "呼吸",
    ghost: "幽灵网格"
  },
  en: {
    none: "None (Static)",
    "static-dim": "Static Dim",
    breathe: "Breathe",
    ghost: "Ghost Grid"
  }
};

export const motionPresetCopy: Record<Language, Record<MotionPresetId, { name: string; description: string }>> = {
  cn: {
    blink: { name: "闪烁", description: "选中点阵同步双闪，适合短促状态反馈。" },
    wave: { name: "波浪", description: "可向上下左右或对角线推进的错峰波浪。" },
    sweep: { name: "扫描", description: "更干净的扫描前沿，带柔和尾迹。" },
    bloom: { name: "扩散", description: "从指定原点向外扩散的亮度波。" },
    "fish-eye": { name: "鱼眼波纹", description: "带轻微鱼眼缩放的对角波纹，节奏更柔和。" },
    ripple: { name: "涟漪", description: "从中心或指定原点向外扩散的径向涟漪。" },
    pulse: { name: "脉冲", description: "所有选中点阵一起呼吸闪动。" },
    spiral: { name: "螺旋", description: "按顺时针螺旋路径依次点亮。" },
    corners: { name: "四角优先", description: "四角先亮，再推进到边缘和中心。" },
    snake: { name: "蛇形", description: "按行列蛇形路径连续游走。" },
    checkerboard: { name: "棋盘", description: "奇偶格分组交替闪烁。" },
    rain: { name: "雨滴", description: "分散落点形成随机雨滴感。" },
    pinwheel: { name: "风车", description: "按角度象限围绕中心旋转推进。" }
  },
  en: {
    blink: { name: "Blink", description: "A compact double-flash preset for selected dots." },
    wave: { name: "Wave", description: "A staggered wave that travels horizontally, vertically, or diagonally." },
    sweep: { name: "Sweep", description: "A clean scanning front with a softer trailing edge." },
    bloom: { name: "Bloom", description: "A center-out bloom that expands from a chosen origin point." },
    "fish-eye": { name: "Fisheye Ripple", description: "A diagonal ripple with subtle fisheye scaling and a softer rhythm." },
    ripple: { name: "Ripple", description: "A radial ripple that fades and scales from an origin point." },
    pulse: { name: "Pulse", description: "All selected dots breathe together like a classic loader." },
    spiral: { name: "Spiral", description: "A clockwise spiral path through the grid." },
    corners: { name: "Corners First", description: "Corners fire first, then edges, then the center." },
    snake: { name: "Snake", description: "A continuous row-by-row snake path through the grid." },
    checkerboard: { name: "Checkerboard", description: "Alternating parity groups pulse in a checker rhythm." },
    rain: { name: "Rain", description: "Deterministic scattered drops create a random-rain loading feel." },
    pinwheel: { name: "Pinwheel", description: "Angular quadrants spin around the center like a pinwheel." }
  }
};
