const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless:true, channel:'chrome'});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror', e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3108/editor');
await page.getByRole('button',{name:'填满点阵',exact:true}).click();
await page.getByRole('button',{name:'预览动画',exact:true}).click();
const panelCombos = page.locator('[data-slot="toolcraft-panel-content"] [role="combobox"]');
const presets = panelCombos.nth(1);
await presets.click();
await page.locator('[role="option"]').first().waitFor({state:'visible'});
const presetCount = await page.locator('[role="option"]').count();
assert.equal(presetCount,44);
await page.keyboard.press('Escape');
for (let index = 0; index < presetCount; index += 1) {
  await presets.click();
  await page.locator('[role="option"]').first().waitFor({state:'visible'});
  await page.locator('[role="option"]').nth(index).click();
  await page.waitForTimeout(100);
  const values=await page.locator('.preview-loader__cell').evaluateAll(es=>es.map(e=>({o:getComputedStyle(e).opacity,t:getComputedStyle(e).transform})));
  assert(values.length >= 72);
  assert(!JSON.stringify(values).includes('NaN'));
}
await presets.click();
await page.locator('[role="option"]').first().waitFor({state:'visible'});
await page.locator('[role="option"]').filter({hasText:'鱼眼镜头'}).click();
const speedSlider=page.getByRole('slider',{name:'速度'});
const scaleSlider=page.getByRole('slider',{name:'缩放强度'});
await speedSlider.press('Home');
for(let i=0;i<25;i+=1) await speedSlider.press('ArrowRight');
await scaleSlider.press('Home');
for(let i=0;i<16;i+=1) await scaleSlider.press('ArrowRight');
await page.waitForTimeout(200);
const before=await page.locator('.preview-loader__cell').evaluateAll(es=>es.map(e=>e.style.opacity));
await page.waitForTimeout(220);
const after=await page.locator('.preview-loader__cell').evaluateAll(es=>es.map(e=>e.style.opacity));
assert.notDeepEqual(before,after,'animation must advance');
await page.screenshot({path:'/tmp/dot-motion-updated.png',fullPage:true});
await page.reload();
assert((await presets.innerText()).includes('鱼眼镜头'));
assert.equal(await speedSlider.getAttribute('aria-valuenow'),'1.5');
assert.equal(await scaleSlider.getAttribute('aria-valuenow'),'80');
await page.getByRole('button',{name:'导出',exact:true}).click();
const exportPlatforms=page.locator('[data-slot="sheet-content"] [data-slot="toggle-group-item"]');
await exportPlatforms.nth(0).click();
const javascript = await page.locator('.export-code').innerText();
const exported = await browser.newPage();
exported.on('pageerror', e=>errors.push(e.message));
await exported.setContent(`<!doctype html><dot-motion-loader></dot-motion-loader><script>${javascript}</script>`);
const first = await exported.evaluate(()=>document.querySelector('body > :first-child').shadowRoot.querySelector('canvas').toDataURL());
await exported.waitForTimeout(200);
const second = await exported.evaluate(()=>document.querySelector('body > :first-child').shadowRoot.querySelector('canvas').toDataURL());
assert(first !== second,'export must animate');
await exported.evaluate(()=>document.querySelector('body > :first-child').pause());
const stopped = await exported.evaluate(()=>document.querySelector('body > :first-child').currentTime);
await exported.waitForTimeout(150);
assert.equal(await exported.evaluate(()=>document.querySelector('body > :first-child').currentTime),stopped);
await exported.evaluate(()=>{const el=document.querySelector('body > :first-child');el.style.width='120px';el.seek(0.5);el.play();});
await exported.waitForTimeout(150);
assert(await exported.evaluate(()=>document.querySelector('body > :first-child').currentTime)>0.5);
assert.deepEqual(await exportPlatforms.allTextContents(), ['JavaScript', 'Swift']);
const downloadPromise=page.waitForEvent('download');
await page.getByRole('button',{name:'下载',exact:true}).click();
const download=await downloadPromise;
assert(download.suggestedFilename().endsWith('.js'));
await download.saveAs('/tmp/DotMotionQA.js');
await exportPlatforms.nth(1).click();
const swiftDownload=page.waitForEvent('download');
await page.getByRole('button',{name:'下载',exact:true}).click();
await (await swiftDownload).saveAs('/tmp/DotMotionView.swift');
await exported.close();
assert.deepEqual(errors,[]);
console.log('PASS: 44 preset switches, fill, playback, speed, scale, persistence, export dialog; no page errors.');
await browser.close();
